"""Fix bug with Mapper

Revision ID: 1da1ac548607
Revises: 5e3724628a31
Create Date: 2024-04-16 22:04:35.327202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da1ac548607'
down_revision: Union[str, None] = '5e3724628a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reaction', sa.Column('type', sa.Enum('LIKE', 'DISLIKE', name='reactiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_reaction', 'type')
    # ### end Alembic commands ###
