"""Fix Mapper notation in CommentResponse

Revision ID: 5dbda7da6c7d
Revises: 1da1ac548607
Create Date: 2024-04-17 22:00:25.427590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbda7da6c7d'
down_revision: Union[str, None] = '1da1ac548607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
