"""Add description field to Theme

Revision ID: 88580dffa10f
Revises: 5dbda7da6c7d
Create Date: 2024-04-19 22:06:33.923186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88580dffa10f'
down_revision: Union[str, None] = '5dbda7da6c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'description')
    # ### end Alembic commands ###
