"""Make field non-nullable belongs_to in CommentReaction

Revision ID: 890e5c7b4e69
Revises: e72dd4907adf
Create Date: 2024-04-25 21:38:51.364117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '890e5c7b4e69'
down_revision: Union[str, None] = 'e72dd4907adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_reaction', 'belongs_to',
               existing_type=postgresql.ENUM('COMMENT', 'RESPONSE', name='reactionowner'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment_reaction', 'belongs_to',
               existing_type=postgresql.ENUM('COMMENT', 'RESPONSE', name='reactionowner'),
               nullable=True)
    # ### end Alembic commands ###
