"""Make Theme.description necessary & add unique constraint on Theme.name

Revision ID: 94d389dac72d
Revises: 88580dffa10f
Create Date: 2024-04-19 22:23:47.288260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d389dac72d'
down_revision: Union[str, None] = '88580dffa10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('theme', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'theme', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'theme', type_='unique')
    op.alter_column('theme', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
