"""Temporarely delete field belongs_to in CommentReaction

Revision ID: b63cad481908
Revises: 5498ac9195d2
Create Date: 2024-04-25 21:35:59.825634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b63cad481908'
down_revision: Union[str, None] = '5498ac9195d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_reaction', 'belongs_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reaction', sa.Column('belongs_to', postgresql.ENUM('COMMENT', 'RESPONSE', name='reactionowner'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
