"""Return field belongs_to in CommentReaction

Revision ID: e72dd4907adf
Revises: b63cad481908
Create Date: 2024-04-25 21:36:48.359493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72dd4907adf'
down_revision: Union[str, None] = 'b63cad481908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_reaction', sa.Column('belongs_to', sa.Enum('COMMENT', 'RESPONSE', 'QUESTION_RESPONSE', name='reactionowner'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_reaction', 'belongs_to')
    # ### end Alembic commands ###
