"""Set up foreing key problem_id in ExplanationImage explicitly

Revision ID: ea63cba6e923
Revises: f3ff04347672
Create Date: 2024-03-21 17:15:46.250011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea63cba6e923'
down_revision: Union[str, None] = 'f3ff04347672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'explanation_image', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'explanation_image', type_='foreignkey')
    # ### end Alembic commands ###
